# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- Olabranch

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: BuildApp
    jobs:
      - job: Build
        displayName: Build Total serve Client Application
        steps:
        - task: NodeTool@0
          inputs:
           versionSpec: '20.x'
          displayName: 'Install Node.js'
        - script: |
            npm install
            npm run build
          displayName: 'npm install and build'
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.BinariesDirectory)'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
            verbose: true
        - task: PublishBuildArtifacts@1
          inputs:
           PathtoPublish: '$(Build.ArtifactStagingDirectory)'
           ArtifactName: 'drop'


  - stage: Deployment 
    displayName: Deployment
    jobs:
      - job: Deployment
        pool:
         vmimage: 'windows-latest'
        displayName: App Depolyment
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
           buildType: 'current'
           downloadType: 'single'
           artifactName: 'drop'
           downloadPath: '$(Build.ArtifactStagingDirectory)'

        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Olaconnection'
            appType: 'webApp'
            WebAppName: 'wapp-olalearning'
            packageForLinux: '$(Build.ArtifactStagingDirectory)/drop/$(Build.BuildId).zip'